name: zwavejs2mqtt nightly build
 
on:
#  push:
#    branches: 
#    - master
#    paths-ignore: #this ensures auto rebuilds don't occure when README.md is updated or the seperate workflow for updating descriptions and readme is modifies
#        - 'README.md'
#        - '.github/workflows/update-dockerhub-description-readme.yml'
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 18 * * *'


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} #set these secrets in your guthub account
          password: ${{ secrets.DOCKERHUB_TOKEN }} #set these secrets in your github account

      - name: Available_platforms 
        run: echo ${{ steps.buildx.outputs.platforms }} #this is for logging

      - name: Builder instance name
        run: echo ${{ steps.buildx.outputs.name }} #this is for logging

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: https://github.com/zwave-js/zwavejs2mqtt.git
          file: ./docker/Dockerfile.contrib
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: scyto/zwavejs2mqtt:master #set to the dockerhub repo this will be pushed to
          cache-from: type=local,mode=max,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache
          build-args: |
             SRC=git-clone-src
             Z2M_BRANCH=master
             ZWJ_BRANCH=master
             YARN_NETWORK_TIMEOUT=30000

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }} #this is for logging.
        
